- README.md
- README.rst
- catalog-info.yaml
This PR changes the filetype of the README, and adds a catalog-info.yaml file.
> docs: Setup the Repository

- frontend-app-discussions/src/i18n/transifex_input.json
Reverts openedx/openedx-translations#23
For testing a failed action
> Revert "chore: add updated translation source files"

- docs/decisions/0001-translations-management.rst
Closes https://github.com/openedx/openedx-translations/issues/3
> fix: update OEP-58 link

- .github/ISSUE_TEMPLATE/translations-request.yml
- .github/workflows/add-TXrequest-to-notify-slack.yml
This PR adds two new files that support the community:
1. An issue request form so community members can request help from the Translation WG on translation file problems
2. Automation to automatically notify the Translations WG on Slack.
> feat: add translations request form and automation

- .github/workflows/extract-translation-source-files.yml
- transifex.yml
tested on my fork https://github.com/brian-smith-tcril/openedx-translations/actions/runs/3998659310/jobs/6861604663
> feat: add frontend-app-learner-dashboard

- .github/workflows/extract-translation-source-files.yml
- transifex.yml
tested on my fork https://github.com/brian-smith-tcril/openedx-translations/actions/runs/3998900587/jobs/6862136026
> feat: add frontend-app-ora-grading

- .github/workflows/extract-translation-source-files.yml
- transifex.yml
Reverts openedx/openedx-translations#84
These repos aren't quite ready to be added yet
> Revert "feat: add python-based repos"

- .github/workflows/extract-translation-source-files.yml
- transifex.yml
Tested: https://github.com/Carlos-Muniz/openedx-translations/actions/runs/4016292744
> feat: add course-discovery to python-based repos

- .github/workflows/extract-translation-source-files.yml
- transifex.yml
tested on my fork https://github.com/brian-smith-tcril/openedx-translations/actions/runs/4015567225/jobs/6897466103
> feat: add paragon

- .github/workflows/extract-translation-source-files.yml
- transifex.yml
This PR needs https://github.com/openedx/RecommenderXBlock/pull/65 before it's merged.
> feat: Add RecommenderXBlock to the translation pipeline

- .github/workflows/extract-translation-source-files.yml
- transifex.yml
feat: Add [DoneXBlock](https://github.com/openedx/DoneXBlock)  to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/DoneXBlock/pull/130 before it's merged.
> feat: Add DoneXBlock  to the translation pipeline

- .github/workflows/extract-translation-source-files.yml
> feat: add admin-portal and publisher mfes

- Makefile
fix: transifex pull is failing - patch for #1373
> fix: transifex pull is failing - patch for #1373

- Makefile
We're syncing the languages from the old project ( https://app.transifex.com/open-edx/edx-platform/ ) to the new project ( https://app.transifex.com/open-edx/openedx-translations/ ) on Transifex.
This pull request includes all supported languages in the Open edX project: 
- https://openedx.atlassian.net/wiki/spaces/COMM/pages/3157524644/Translation+Working+Group#The-following-is-a-table-of-the-latest-list-of-languages-supported--by-the-Translation-Working-Group
Another update is required to include all the languages that might be supported in the future. [Related discussion on Slack](https://openedx.slack.com/archives/C037XDB9KN1/p1696870236377009).
This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation …
> feat: sync all supported langs

- Makefile
- scripts/rerun_tests_for_transifex_bot_pull_requests.sh
I'll update docs in another PR: 
- https://github.com/openedx/openedx-translations/pull/1928
> feat: make command to re-run tests for translation PRs - FC-0012

- .github/workflows/extract-translation-source-files.yml
This adds an input to the extract translation source files workflow to allow manual runs that only extract source translation files for an individual repository.
> feat: dynamic matrix for individual repo source file extraction

- .github/workflows/sync-translations.yml
> feat: add ecommerce to sync-translations.yml

- .github/workflows/extract-translation-source-files.yml
- transifex.yml
Depends on another pull request:
- Please don't merge unless: https://github.com/openedx/frontend-platform/pull/647 is merged.
- Tested on my fork: https://github.com/Zeit-Labs/openedx-translations/commit/c84aee0fc12c44eeeb43d81aac2bc99ec3138a61 ✅ 
> feat: extract from frontend-platform | FC-0012

- catalog-info.yaml
Updating the catalgo-info.yaml file per: https://docs.openedx.org/projects/openedx-proposals/en/latest/processes/oep-0055/decisions/0004-release-data-in-catalog-info-files.html
> feat: Add translations to the release.

- .gitignore
Added .idea directory to `.gitignore` file.
> chore: Added .idea directory to .gitignore.

- transifex.yml
```
There were some errors in your configuration file
FILTERS SET 1
source_file: Should be a valid path
source_file_dir: Unknown field.
source_file_extension: Unknown field.
FILTERS SET 2
source_file: Should be a valid path
source_file_dir: Unknown field.
source_file_extension: Unknown field.
```
> fix: invalid ios/android transifex.yml configs fixed

- .github/workflows/validate-translation-files.yml
Tested by adding a `.po` file change: https://github.com/openedx/openedx-translations/actions/runs/10561099919
> fix: install requirements before validating translations

- transifex.yml
- Similar to https://github.com/openedx/openedx-translations/pull/7638 but for the main project.
- Related issue: https://github.com/openedx/wg-translations/issues/43
> feat: pull onlyreviewed translations for main project

- transifex.yml
- Similar to https://github.com/openedx/openedx-translations/pull/7638 but for Sumac.
- Related issue: https://github.com/openedx/wg-translations/issues/43
> feat: pull onlyreviewed translations for Sumac
