openedx/openedx-translations

README.rst

This PR updates the README in openedx-translations to contain more details about how its used, and the current state of usage related to the prototype for OEP-58.
Related to https://github.com/openedx/open-edx-proposals/pull/367

docs: update the README about prototype

---

transifex.yml

Adds the configuration needed to automatically upload translation source files from MFEs to Transifex and to put them in the right place once translated.
The yaml was tested in the [Transifex project openedx-sandbox](https://www.transifex.com/open-edx/openedx-sandbox)
And its ability to download back into the right place was tested in https://github.com/openedx/openedx-translations/pull/20

feat: add MFEs to transifex.yml

---

.github/workflows/extract-translation-source-files.yml

by using `continue-on-error` (https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures), translation extraction on a single repo will not stop extraction from running on the rest of the repos

fix: continue extraction when a repo fails

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

Python-based repos with correct configuration (api-doc-tools, blockstore,
course-discovery, and edx-enterprise) have been added to the workflow and
transifex.yml.

feat: add python-based repos

---

.github/workflows/extract-translation-source-files.yml

Noticed that the commit messages for the python translation job has an unnecessary "translation".

fix: remove "translations" from python commit msg

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

The repository seems ready and the error message is from the message itself.
`make extract_translations` seems to be working properly.
The message below is not an error. It's a translation for the [FormattedMessage in the ErrorPage](https://github.com/openedx/frontend-lib-content-components/blob/61c99b9b4051f0269114555655b4e28ee71e41cf/src/editors/sharedComponents/ErrorBoundary/ErrorPage.jsx#L27-L47).
frontend-lib-content-components `$ cat src/i18n/transifex_input.json`
```
{
"unexpected.error.message.text": "An unexpected error occurred. Please click the button below to refresh the page.",
"unexpected.error.button.text": "Try again"
}
```
Proposal: OEP-0058 
Project: FC-0012

feat: Add frontend-lib-content-components

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

Mostly path changes to ensure studio-frontend matches other repos i18n structure.
This PR needs https://github.com/openedx/studio-frontend/pull/374 before it's merged.

chore: standarize studio-frontend MFE i18n pattern

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

The package newly included MFE Standard i18n pattern.
Tested on my fork: https://github.com/Zeit-Labs/openedx-translations/actions/runs/4428707205/jobs/7768197651
Needs: https://github.com/openedx/frontend-lib-special-exams/pull/85 before this can be merged
Refs: FC-0012 OEP-0058

feat: add frontend-lib-special-exams

---

.github/workflows/echo-actor-name-and-id.yml

This adds a temporary workflow to get the actor name and ID for use in implementing automerge functionality. This will be removed as a part of the automerge PR.

chore: add workflow to verify PR actor name and id

---

.github/workflows/automerge-transifex-app-prs.yml

The CLA check prevents the [transifex github app](https://github.com/apps/transifex-integration) from committing directly, so we have configured it to create PRs instead. This adds a workflow to automatically merge those PRs.
This is done by checking `github.actor` and `github.actor_id` ([docs](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)) against the repository secret values `TRANSIFEX_APP_ACTOR_NAME` and `TRANSIFEX_APP_ACTOR_ID`, and running `gh pr merge` if they match.

feat: automatically merge PRs from transifex github app

---

.github/workflows/automerge-transifex-app-prs.yml

The `--rebase` option could be causing race conditions.
It seems that `--rebase` is redaundant for the following reasons:
- Each automatic Transifex pull request updates a single translation file.
- The translations files are not touched, except by automatic Transifex PRs.
- In the case of conflicts `--rebase` won't help because conflicts needs manual resolution.
- When having two competing PRs due to, for example, timing issues closing them or merging one of them could result into stale translations which will be fixed in the next round of automatic PRs.
Refs: [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) implementing Translation Infrastructure OEP-58.

fix: automerge transifex PRs without --rebase

---

.github/workflows/automerge-transifex-app-prs.yml

Non-interactive merging using `gh pr merge` requires setting a merge type flag. This updates the action to use `--merge`.

fix: use `--merge` flag to automerge transifex PRs

---

.github/workflows/automerge-transifex-app-prs.yml

The retry on the transifex automerge action was missing a required retry parameter. This updates the action to have the required timeout.

fix: add required timeout to automerge retry

---

.github/workflows/extract-translation-source-files.yml

fix: include `.po` files even if they are ignored
Some repos have `.po` files ignored in .gitignore. Adding `django.po` and `djangojs.po` will fail in the pipeline process because of that. We resolve the issue by forcing git to include these files even if they are ignored in the source repo
This bug was introduced while adding [xblock-submit-and-compare](https://github.com/openedx/xblock-submit-and-compare) to the translation pipeline. See https://github.com/openedx/openedx-translations/pull/201

fix: include .po files even if they are ignored

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add xblock-drag-and-drop-v2 to the translation pipeline
**IMPORTANT**: This PR needs https://github.com/openedx/xblock-drag-and-drop-v2/pull/316 before it's merged.
Refs: see details [here](https://github.com/openedx/xblock-drag-and-drop-v2/pull/316)

feat: Add xblock-drag-and-drop-v2 to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [xblock-lti-consumer](https://github.com/openedx/xblock-lti-consumer) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/xblock-lti-consumer/pull/341 before it's merged.
Refs:
see details [here](https://github.com/openedx/xblock-lti-consumer/pull/341)

feat: Add xblock-lti-consumer to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [xblock-qualtrics-survey](https://github.com/openedx/xblock-qualtrics-survey) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/xblock-qualtrics-survey/pull/73 before it's merged.
Refs:
see details [here](https://github.com/openedx/xblock-qualtrics-survey/pull/73)

feat: Add xblock-qualtrics-survey to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [xblock-submit-and-compare](https://github.com/openedx/xblock-submit-and-compare) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/xblock-submit-and-compare/pull/96 before it's merged.
Refs:

feat: Add xblock-submit-and-compare to the translation pipeline

---

Makefile

The makefile had `alow-unsafe`. This updates it to have `allow-unsafe`

fix: update makefile to fix typo

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [completion](https://github.com/openedx/completion) to the translation pipeline
**IMPORTANT:** This PR needs This PR needs https://github.com/openedx/completion/pull/232 before it's merged. before it's merged.
Refs:

feat: Add completion to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [edx-ora2](https://github.com/openedx/edx-ora2) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/edx-ora2/pull/1932 before it's merged.
Refs:

feat: Add edx-ora2 to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [edx-proctoring](https://github.com/openedx/edx-proctoring) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/edx-proctoring/pull/1124 before it's merged.
Refs:

feat: Add edx-proctoring to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [edx-ace](https://github.com/openedx/edx-ace) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/edx-ace/pull/212 before it's merged.
Refs:

feat: Add edx-ace to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [edx-bulk-grades](https://github.com/openedx/edx-bulk-grades) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/edx-bulk-grades/pull/151 before it's merged.
Refs:

feat: Add edx-bulk-grades to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml

feat: Add compile validation step for translation
Compile extracted messages to verify that it will pass in transifex
It happened with one repository and it can happen to others. The process passed here but failed in transifex because of a duplicated msg. To avoid that, we're adding `compilemessages` step after messages extraction to verify that it'll pass in transifex and to catch related errors before merging

feat: Add compile validation step for translation

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [xblock-free-text-response](https://github.com/openedx/xblock-free-text-response) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/xblock-free-text-response/pull/111 before it's merged.
Refs:

feat: Add xblock-free-text-response to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [xblock-sql-grader](https://github.com/openedx/xblock-sql-grader) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/xblock-sql-grader/pull/100 before it's merged.
Refs:

feat: Add xblock-sql-grader to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [AudioXBlock](https://github.com/openedx/AudioXBlock/pull/89) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/AudioXBlock/pull/89 before it's merged.
Refs:

feat: Add AudioXBlock to the translation pipeline

---

.github/workflows/fix-transifex-resource-names.yml

`fix_transifex_resource_names.py` requires a Transifex API token. We have this token stored in the repo as a secret. This PR updates the actions workflow to provide the token to the script as an environment variable.

fix: provide secret transifex api token via env

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [xblock-image-explorer](https://github.com/openedx/xblock-image-explorer) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/xblock-image-explorer/pull/105 before it's merged.
Refs:

feat: Add xblock-image-explorer to the translation pipeline

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [xblock-google-drive](https://github.com/openedx/xblock-google-drive) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/xblock-google-drive/pull/58 before it's merged.
Refs:

feat: Add xblock-google-drive to the translation pipeline

---

requirements/pip.txt
requirements/pip_tools.txt
requirements/test.txt
requirements/transifex-resources.txt
requirements/translations.txt

Upgrading requirements using `make upgrade`
The main reason is to have `edx-i18n-tools==1.0.0` so we can include [this fix](https://github.com/openedx/i18n-tools/pull/129) in the process

feat: upgrade requirements to have the edx-i18n-tools 1.0.0

---

.github/workflows/extract-translation-source-files.yml

My bad! the key I used for these repositories was `repo` which is wrong. The correct one is `repo_name`

fix: Fix wrong key (repo) to be (repo_name)

---

.github/workflows/extract-translation-source-files.yml

The fix amends an outdated matrix yaml config.

docs: fix typo `module_name` -> `python_module_name`

---

.github/workflows/validate-translation-files.yml
.gitignore
Makefile

- A step towards https://github.com/openedx/openedx-translations/issues/549
- More work to follow on the Transifex pull request workflow
----

feat: validate po files on pull_request

---

.github/workflows/validate-translation-files.yml

This helps to avoid breaking PR builds due to translation issues even though it's not the PR's fault.
------

fix: validate translation files only when it's changed

---

.github/workflows/extract-translation-source-files.yml

feat: Special support for XBlocks
XBlocks require `text.po` and `textjs.po` instead of `django.po` and `djangojs.po`. This PR will add support to find XBlock translation files and rename them to `django` during translation extraction.
**Why is this needed?**
After moving along with standardizing `make extract_translations` in XBlocks; we found that it's safer to keep `text.po` and `textjs.po` as the translation domains for XBlocks. It's to preserve compatibility with in-repo translations since it'll be used for a while by the community
See this related conversation https://github.com/openedx/edx-cookiecutters/pull/382#discussion_r1300041928

feat: Special support for XBlocks

---

.github/workflows/fix-transifex-resource-names.yml
.gitignore
Makefile
requirements/pip.txt
requirements/pip_tools.txt
requirements/test.in
requirements/test.txt
requirements/transifex.txt
requirements/translations.txt
scripts/fix_transifex_resource_names.py
scripts/tests/test_fix_transifex_resource_names.py

- chore: add pytest-cov
- feat: fix resource names monthly: To give some time leeway for Transifex to add new resources as opposed to expect it to add the resource immediately after a pull request is merged.
- feat: fix random and lengthy slugs and support `-js` suffix
<details><summary>Test results</summary>
```
$ make fix_transifex_resource_names
python scripts/fix_transifex_resource_names.py
Updating openedx-translations project resource and slug names:
------------
Updating:
Resource id: o:open-edx:p:openedx-translations:r:audioxblock
Resource slug: audioxblock
Resource name: AudioXBlock
Resource categories: github#repository:openedx/openedx-translations#branch:main#path:translations/AudioXBlock/audio/conf/locale/en/LC_MESSAGES/django.po
Skipping: "AudioXBlock" because it seems to …
```

feat: fix random and lengthy slugs and support `-js` suffix

---

.github/workflows/validate-translation-files.yml

The `validate-translation-files.yml` workflow is now required, but it runs only on PRs in which `translations/**` have been edited.
This causes the non-translation pull requests to be blocked from merging because the `validate-translation-files.yml` won't run despite being required.
Related issues:
- https://github.com/openedx/openedx-translations/issues/1003

fix: allow merging non-translations pull requests

---

.github/workflows/sync-translations.yml
Makefile
requirements/pip.txt
requirements/pip_tools.txt
requirements/test.in
requirements/test.txt
requirements/transifex.txt
requirements/translations.in
requirements/translations.txt
scripts/sync_translations.py
scripts/tests/response_data.py
scripts/tests/test_sync_translations.py

This is an on-demand GitHub Actions workflow which will sync traslations and their status from the `open-edx/edx-platform` Transifex project (old) into `open-edx/openedx-translations` OEP-58 project (new).
This is to address https://github.com/openedx/edx-platform/pull/32994#issuecomment-1680054505 on preserving the translated/reviewed status when migrating to the new project.
This PR replaces https://github.com/openedx/openedx-translations/pull/569

feat: sync from old transifex project

---

.github/workflows/sync-translations.yml

fix: set max-parallel: 1 to avoid transifex (Throttled)
without the limit, we'll face an exception `transifex.api.jsonapi.exceptions.JsonApiException_429_throttled`

fix: set max-parallel: 1 to avoid transifex (Throttled)

---

requirements/pip_tools.txt
requirements/test.txt
requirements/translations.txt

Upgrade requirements to include the latest `edx-i18n-tools==1.3.0`

Upgrade requirements to include the latest edx-i18n-tools

---

Makefile

Otherwise it's a faulty code. Also corrected in the [Confluence table](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3157524644/Translation+Working+Group#The-following-is-a-table-of-the-latest-list-of-languages-supported--by-the-Translation-Working-Group).

fix: es-419 --> es_419 to match Transifex code

---

Makefile

See: https://www.studiodessuantbone.com/articles/what-is-es_419/
This one reserves a `:faceplam:` emoji 😅 after https://github.com/openedx/openedx-translations/pull/1485. The title was correct, but the code wasn't.
Also, [the table](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3157524644/Translation+Working+Group#The-following-is-a-a-table-of-lanague-that-are-supporetd--last-updated) has been fixed.

fix: typo in the code of es_419

---

.github/workflows/automerge-transifex-app-prs.yml

otherwise it'll complain a lot about mergedAt being null such as: https://github.com/openedx/openedx-translations/actions/runs/6153503626/job/16697476155

fix: don't fail after merging Transifex GitHub App pull requests FC-0012

---

.github/workflows/validate-translation-files.yml
Makefile
scripts/validate_translation_files.py

Locating the validation error can be difficult in the GitHub Actions check.
Post a comment (e.g. https://github.com/openedx/openedx-translations/pull/1894#issuecomment-1768893221) in the pull request with failed translations.
The comments are "sticky" to avoid spamming the pull requests with multiple comments. 
This won't affect us because bots writes directly to this repository. 
<details><summary>Testing results with screenshots</summary>
- Successful validation: ![image](https://github.com/openedx/openedx-translations/assets/645156/da5dffd9-dd60-40a0-b8ce-ae0cfc55fd73)
- Failed result: ![image](https://github.com/openedx/openedx-translations/assets/645156/0d5af732-973b-4dd9-a2f6-c919a576caec)
</details> 
This contribution is part of the [FC-0012 …

feat: post translation validation errors as a GitHub comment | FC-0012

---

.github/workflows/validate-translation-files.yml

The comment step is failing and causing pull requests from forks to be unmergeable.

fix: allow merging forks pull requests

---

README.rst

- Update repo status
- Fix readme typos and formatting errors
- Document Makefile commands and admin tools

docs: reflect latest updates in README - FC-0012

---

.github/workflows/validate-translation-files.yml

This now a proper check. Finally, I've got the `if: always && ...` part right!
<details><summary>Details</summary>
- Tested in this (fork) pull request and the step was skipped: ![image](https://github.com/openedx/openedx-translations/assets/645156/6ffeb967-4262-45cf-80fa-185bdca73ea5)
- Tested in [another (source) pull request](https://github.com/openedx/openedx-translations/pull/1931) and the step was successful! 
</details>

feat: require the validation comment on non-fork PRs

---

.github/workflows/python-tests.yml
scripts/tests/mock_translations_dir/demo-xblock/conf/locale/ar/LC_MESSAGES/django.po
scripts/tests/mock_translations_dir/demo-xblock/conf/locale/de_DE/LC_MESSAGES/django.po
scripts/tests/mock_translations_dir/demo-xblock/conf/locale/en/LC_MESSAGES/django.po
scripts/tests/mock_translations_dir/demo-xblock/conf/locale/hi/LC_MESSAGES/django.po
scripts/tests/test_fix_transifex_resource_names.py
scripts/tests/test_sync_translations.py
scripts/tests/test_validate_translation_files.py
scripts/validate_translation_files.py

- fixes the exception shown in the comment: https://github.com/openedx/openedx-translations/pull/1611#issuecomment-1770897544:
```
Traceback (most recent call last):
File 
"/home/runner/work/openedx-translations/openedx-translations/scripts/validate_translation_files.py",
line 70, in <module>
main()
File 
"/home/runner/work/openedx-translations/openedx-translations/scripts/validate_translation_files.py",
line 47, in main
result = validate_translation_file(po_file)
File 
"/home/runner/work/openedx-translations/openedx-translations/scripts/validate_translation_files.py",
line 27, in validate_translation_file
completed_process = subprocess.run(
File "/usr/lib/python3.10/subprocess.py", line 505, in run
stdout, stderr = process.communicate(input, timeout=timeout)
File …
```

fix: validate_translation works even with unicode errors

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

feat: Add [credentials-themes](https://github.com/openedx/credentials-themes) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/credentials-themes/pull/613 before it's merged.
Refs:

feat: Add credentials-themes to the translation pipeline

---

.github/workflows/python-tests.yml
.github/workflows/validate-translation-files.yml

@brian-smith-tcril I think this will work based on https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths

Only run Python tests when PR contains more than .po's

---

.github/workflows/extract-translation-source-files.yml

When running the `extract-translation-source-files` workflow via dispatch `selectedRepo` pulls from `inputs.repo` which is always a string (but can be an empty string).
The logic throughout the rest of the workflow assumes an empty string, but fails with null or undefined.
This just add a null coalesce that defaults `selectedRepo` to an empty string so the rest of the logic works.

fix: ensure we have an empty string instead of null for `selectedRepo`

---

.github/workflows/extract-translation-source-files.yml

feat: Add [ecommerce](https://github.com/openedx/ecommerce) to the translation pipeline
Refs:

feat: Add ecommerce to the translation pipeline

---

Makefile

docs: add link to the supported languages list in Confluence

---

.github/workflows/automerge-transifex-app-prs.yml
.github/workflows/validate-translation-files.yml
scripts/tests/test_validate_translation_files.py
scripts/validate_translation_files.py

- fix: avoid failing the automerge-transifex-app-prs.yml 
- fix: add default failure message if nothing is printed on stdout
- chore: use argparse on validate_translation_files.py 

feat: misc fixes for FC-0012 scripting

---

.github/workflows/extract-translation-source-files.yml

feat: Add [edx-enterprise](https://github.com/openedx/edx-enterprise) to the translation pipeline
**IMPORTANT:** This PR needs https://github.com/openedx/edx-enterprise/pull/1751 before it's merged.
Refs:

feat: Add edx-enterprise to the translation pipeline

---

.github/workflows/automerge-transifex-app-prs.yml

This reverts commit https://github.com/openedx/openedx-translations/commit/854ceef60fdeb48cab6087df34f7a1c9722632b5, but increase `retry_wait_seconds` to 180 and use bash if-statement.
There has been new failures which prevented such as:
> GraphQL: Pull request Pull request is in unstable status (enablePullRequestAutoMerge)
as well as the interminent error of:
> auto-merge was automatically disabled yesterday
> Base branch was modified
This effectively brings back both https://github.com/openedx/openedx-translations/pull/222 and https://github.com/openedx/openedx-translations/pull/225.
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update …

fix: revert: avoid failing the automerge-transifex-app-prs.yml 

---

transifex.yml

feat: add missing repos to transifex.yml
I forgot to add them in the original PRs
ecommerce: https://github.com/openedx/openedx-translations/pull/2181
edx-enterprise: https://github.com/openedx/openedx-translations/pull/2179
edx-platform: https://github.com/openedx/openedx-translations/pull/1275
Refs:

feat: add missing repos to transifex.yml

---

.github/workflows/sync-translations.yml
scripts/sync_translations.py
scripts/tests/test_sync_translations.py

We've done about 200 manual fix on the https://app.transifex.com/open-edx/openedx-translations/ to fix translation validation issues in PRs such as https://github.com/openedx/openedx-translations/pull/1577/commits/d1ddaa7fef356de96608128c151570e766f4cf1e. 
Those changes would be overridden on the next sync and needs to be fixed again.
For more information, please check [this Slack Thread](https://openedx.slack.com/archives/C04R6TUJB7T/p1699457188895449) about the problem.
This pull request will only update the translation string if new translation is found:
```
newer_translation_found = new_project_translation_time > old_project_translation_time
```
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation …

fix: avoid overriding manual edits for newer entries

---

docs/decisions/0002-mark-fuzzy-entries.rst

This adds an ADR for the rejected proposal of the #1944 pull request. Full details in the other pull request.

docs: rejected proposal the fuzzy strings

---

.github/workflows/fix-transifex-resource-names.yml

It puzzles me every time I try to locate the workflow in the GitHub Actions UI.

fix: rename fix-transifex-resource-names.yml titles

---

catalog-info.yaml

This is going to be used in production by Redwood. I'm making this pull request to mark it appropriately.

chore: mark this repo as production | FC-0012

---

.github/workflows/extract-translation-source-files.yml

- Adds a helpful `ref` option to the GitHub manual trigger action UI.
- Allow running from forks as opposed to only `openedx`
<kbd>![image](https://github.com/openedx/openedx-translations/assets/645156/6fb2897d-e00e-4804-a937-5378d540bb58)</kbd>

feat: trigger extract-translation-source-files with custom branch | FC-0012

---

.github/workflows/extract-translation-source-files.yml
.gitignore

__Jira Ticket:__ [ENT-8221](https://2u-internal.atlassian.net/browse/ENT-8221)
__Description:__
This PR enables translations for `frontend-app-learner-portal-enterprise` repo. The required commands have already been added to the `Makefile` of `frontend-app-learner-portal-enterprise` (https://github.com/openedx/frontend-app-learner-portal-enterprise/blob/master/Makefile#L44-L67).
**Note:** I was not able to test this via the instructions in https://docs.openedx.org/en/latest/developers/how-tos/enable-translations-new-repo.html#id7 However, I have tested the flow using my own Transifex account.

feat: Enabled translations for frontend-app-learner-portal-enterprise

---

transifex.yml

This PR adds `frontend-app-learner-portal-enterprise` to `transifex.yml` so that translations for this repo start syncing with Transifex.

fix: Added frontend-app-learner-portal-enterprise to transifex.yml

---

transifex.yml

This entry has been missing so translations wasn't making it into this repo from Transifex.

fix: add frontend-app-admin-portal to transifex.yml

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

It's been a while since I've done one of these, so it's entirely possible I missed a step here.

feat: Add platform-plugin-aspects repo to translations

---

.github/workflows/release-project-sync.yml
scripts/release_project_sync.py
scripts/tests/response_data.py
scripts/tests/test_release_project_sync.py

Sync reviews and tags from the `openedx-translations` project into `openedx-translations-<release-name>` projects.

feat: release_project_sync script for review sync

---

scripts/release_project_sync.py
scripts/tests/test_release_project_sync.py

Fix error in environment variable name that breaks the CI builds on GitHub Actions.
Error in CI builds: https://github.com/openedx/openedx-translations/actions/runs/9410676907/job/25922716879
```
Notice:  A new release of pip is available: 23.0.1 -> 24.0
Notice:  To update, run: pip install --upgrade pip
Traceback (most recent call last):
File "./scripts/release_project_sync.py", line 292, in <module>
main()  # pragma: no cover
File "./scripts/release_project_sync.py", line 288, in main
command.run()
File "./scripts/release_project_sync.py", line 227, in run
main_project = self.get_transifex_project(project_slug=MAIN_PROJECT_SLUG)
File "./scripts/release_project_sync.py", line 61, in get_transifex_project
tx_api_token = config['https://www.transifex.com']['password']
File …
```

fix: TRANSIFEX_API_TOKEN name corrected

---

scripts/release_project_sync.py

Transifex sometimes raises DoesNotExist while others JsonApiException.
Catching both types for more solid error handling.
I've refactored the init method.

fix: broader transifex exceptions to workaround exception inconsistency

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

- Add https://github.com/openedx/openedx-app-ios to the list of supported repositories.
- Added support for optional translation requirements through `before_translate` step.
This pull request is part of the [FC-0055 project](https://openedx.atlassian.net/l/cp/nSkaHb7G) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html) for mobile apps.

feat: add mobile apps and with support for pre-extract step | FC-55

---

requirements/test.txt
requirements/translations.txt

See: https://github.com/openedx/wg-build-test-release/issues/383

chore: update Django to 3.2.25 for Redwood - Security Patch

---

translations/edx-platform/conf/locale/ar/LC_MESSAGES/django.po

This one was a high-profile string with a bad variable, causing errors on the site.

fix: Hand-fix a broken ar translation

---

.github/workflows/extract-translation-source-files.yml
transifex.yml

Add [frontend-app-ora](https://github.com/openedx/frontend-app-ora) to list of MFEs with openedx-translation-managed translations.

feat: extract translations from frontend-app-ora

---

transifex.yml

This pull request uses the new `mode: onlyreviewed` feature recently released by Transifex:
- https://community.transifex.com/t/configure-translation-file-modes-for-git-repo-integrations/4465
- https://community.transifex.com/t/github-integration-sync-only-reviewed-strings/3831/14
The documentation has no clear mention of `onlyreviewed` therefore we need to merge this pull request before it can be tested.
- Related issue: https://github.com/openedx/wg-translations/issues/43
- Transifex GitHub Integration settings will be changed from `Reviewed: 100%` to `Reviewed: 30%` to make it more usable for translators. We can play with the numbers as we wish later.

feat: use onlyreviewed for Redwood

---

scripts/fix_transifex_resource_names.py
scripts/release_project_sync.py
scripts/tests/test_release_project_sync.py

- Fixes for the sync translations workflow
- Use `bulk_update` for faster updates
- Sync translations if missing
- Sync tags
- Sync reviews (already there, but noting the feature for reviewers)
Example successful runs:
- Arabic only (32 minutes): https://github.com/openedx/openedx-translations/actions/runs/12694941615
- All languages for a single resource (7 minutes): https://github.com/openedx/openedx-translations/actions/runs/13202683973  
- All languages for all resources (in progress): https://github.com/openedx/openedx-translations/actions/runs/13207292396

feat: bulk_update translation and reviews

---

.github/workflows/fix-transifex-resource-names.yml
Makefile
scripts/fix_transifex_resource_names.py
scripts/tests/test_fix_transifex_resource_names.py

Use release name as a suffix in resource names as a workaround for the branch name duplication issue:
-  #41695
A random suffix is used e.g. `r3231` to denote that this is a unique slug to avoid adding needless suffix after multiple runs. The script should be safe to run multiple times.
The suffix is also useful just in case we had a resource that collides with a release name e.g. `github.com/openedx/xblock-redwood.git` which would be misclassified as a unique slug even though the name is actually reused across projects.
This sort of naunce that might save a day or two in debugging.
GitHub Workflow:
- Changed input parameter from transifex_project_slug to release_name
- Used default maigc value of `main`
- Changed environment variable from TRANSIFEX_PROJECT_SLUG to RELEASE (a transparent …

feat: unique resource slugs
